- name: install and run nginx
  hosts: web
  become: yes
  tasks:
    - name: install nginx
      ansible.buildin.dnf:
        name: nginx
        state: latest
    - name: run nginx
      ansible.buildin.service:
        name: nginx
        state: started
        enabled: yes
